server:
  port: 8085

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j.circuitbreaker:
  circuitBreakerAspectOrder: 1
  instances:
    serviceRegisterSeller:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
      ignoreExceptions:
          - com.martins.orderManagementApp.service.MyException
    serviceGetSellersList:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

resilience4j.retry:
  retryAspectOrder: 2
  instances:
    retryServiceRegisterSeller:
      maxRetryAttempts: 5
      waitDuration: 10000

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true